"use client"

import * as React from "react"
import type { ColumnDef } from "@tanstack/react-table"
import { Check, Link2, Pencil, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { StatusBadge } from "@/components/shared/status-badge"
import { ColumnHeader } from "@/components/shared/column-header"
import { useTranslation } from "@/lib/i18n/i18n-context"
import { cn, formatDateTime } from "@/lib/utils"
import type { StockMovementRow } from "@/lib/hooks/use-inventory"

// Otherwise a pure history/view — no add/delete/approve affordances anywhere
// on it (see the Daily Report panel wiring, which passes neither canAdd nor
// canDelete). Approving a movement stays exactly where it already was, on
// Inventory > In & Out — only editing (onEdit, inventory:edit-gated) was
// added here, so a wrong quantity/reason can be fixed without leaving the
// Daily Report page.

// 'pending'/'approved'/'rejected' (see the stock_movement_rejection
// migration) are the three real statuses this app has (see
// ApprovalStatusBadge on the In & Out page) — matches that badge's tones
// exactly so a movement reads the same way in both places.
function InventoryStatusBadge({ status }: { status: StockMovementRow["status"] }) {
  const { t } = useTranslation("status")
  if (status === "pending") return <StatusBadge tone="warning" label={t("pending")} />
  if (status === "rejected") return <StatusBadge tone="danger" label={t("rejected")} />
  return <StatusBadge tone="success" label={t("approved")} />
}

// A "Manual" tag next to the reason, so an admin-typed entry (Restock/
// Return/Damaged/Adjustment) reads as clearly distinct from one a trigger
// wrote (Sale/Filter Change/Repair) at a glance — those already read as
// self-evidently system-generated by their reason text alone, so nothing is
// added there to avoid cluttering every row with a redundant tag. Same
// treatment as the In & Out Summary's own stock-movements-columns.tsx.
function ReasonCell({ row }: { row: StockMovementRow }) {
  const { t } = useTranslation("inventory")
  return (
    <span className="inline-flex items-center gap-1.5">
      {row.reason}
      {row.source === "Manual" && <StatusBadge tone="neutral" label={t("manualEntry")} />}
    </span>
  )
}

// Approve / Reject on a pending row, right in the Inventory List — approving
// applies the stock change at once (the database's approval trigger takes it
// OUT for fitted filters/parts/units, back IN for returned parts). A row
// combining several movements acts on all of them. A row not yet mapped to
// a stock item (an install model / hand-typed part) can't be approved until
// it is, so it offers Map item instead, which opens the review queue.
function ApprovalActionsCell({
  movement,
  onApprove,
  onReject,
  onMap,
}: {
  movement: StockMovementRow
  onApprove: (movement: StockMovementRow) => void
  onReject: (movement: StockMovementRow) => void
  onMap: (movement: StockMovementRow) => void
}) {
  const { t } = useTranslation("inventory")
  const { t: tCommon } = useTranslation("common")
  if (movement.status !== "pending") return null
  const stop = (fn: () => void) => (e: React.MouseEvent) => {
    e.stopPropagation()
    fn()
  }
  return (
    <div className="flex items-center gap-1">
      {movement.productId ? (
        <Button size="sm" className="h-7 gap-1 px-2" onClick={stop(() => onApprove(movement))}>
          <Check className="h-3.5 w-3.5" /> {tCommon("approve")}
        </Button>
      ) : (
        <Button size="sm" variant="outline" className="h-7 gap-1 px-2" onClick={stop(() => onMap(movement))}>
          <Link2 className="h-3.5 w-3.5" /> {t("mapItem")}
        </Button>
      )}
      <Button
        size="sm"
        variant="ghost"
        className="h-7 w-7 p-0 text-danger"
        aria-label={tCommon("reject")}
        title={tCommon("reject")}
        onClick={stop(() => onReject(movement))}
      >
        <X className="h-3.5 w-3.5" />
      </Button>
    </div>
  )
}

function EditButtonCell({
  movement,
  onEdit,
  className,
}: {
  movement: StockMovementRow
  onEdit: (movement: StockMovementRow) => void
  className?: string
}) {
  const { t } = useTranslation("common")
  return (
    <Button
      size="sm"
      variant="ghost"
      className={className}
      aria-label={t("edit")}
      onClick={(e) => {
        e.stopPropagation()
        onEdit(movement)
      }}
    >
      <Pencil className="h-4 w-4" />
    </Button>
  )
}

// A row's quantity is (almost) always entirely on one side — quantityAdded
// XOR quantityRemoved — for every write path in this app (manual entries,
// the sale-item trigger, the filter-change deduction). Falls back to
// showing both if a row genuinely has both set, rather than silently
// dropping one.
function movementTypeAndQty(row: StockMovementRow): { type: "add" | "deduct" | "addDeduct"; qty: number } {
  if (row.quantityAdded > 0 && row.quantityRemoved > 0) {
    return { type: "addDeduct", qty: row.quantityAdded - row.quantityRemoved }
  }
  if (row.quantityRemoved > 0) return { type: "deduct", qty: row.quantityRemoved }
  return { type: "add", qty: row.quantityAdded }
}

const TYPE_KEYS = { add: "typeAdd", deduct: "typeDeduct", addDeduct: "typeAddDeduct" } as const

function TypeCell({ row }: { row: StockMovementRow }) {
  const { t } = useTranslation("inventory")
  const { type } = movementTypeAndQty(row)
  return <span className={type === "deduct" ? "text-danger" : "text-success"}>{t(TYPE_KEYS[type])}</span>
}

function QtyCell({ row }: { row: StockMovementRow }) {
  const { type, qty } = movementTypeAndQty(row)
  return <span className="font-medium">{type === "deduct" ? `-${qty}` : `+${qty}`}</span>
}

// The Daily Report panel's full column set — shown directly in the compact
// panel (horizontally scrollable, see daily-report-section.tsx's own
// tableClassName="min-w-max") as well as the Maximize2 dialog, which
// renders these exact same columns now that there's no narrower compact
// set held back from it.
//
// onEdit omitted (a technician, or an admin without inventory:edit) falls
// back to the plain column set with no trailing Edit column at all — same
// on/off convention every other Daily Report column set already uses for
// its own admin-only affordances.
// How much of the Inventory List fits the panel's width (see
// inventoryListDensityForWidth): "full" every column; "medium" drops
// Created By / Approved By / Time; "compact" folds Type, Quantity, Reason
// and Status under the item name and puts Edit beside Approve, leaving
// Item | Related Job | actions — so a narrow panel never scrolls sideways.
export type InventoryListDensity = "full" | "medium" | "compact"

export function inventoryListDensityForWidth(width: number): InventoryListDensity {
  if (width >= 1180) return "full"
  if (width >= 760) return "medium"
  return "compact"
}

function CompactItemCell({ row }: { row: StockMovementRow }) {
  const { t } = useTranslation("inventory")
  const { type, qty } = movementTypeAndQty(row)
  return (
    <div className="min-w-0 max-w-[16rem]">
      <div className="truncate font-medium" title={row.productName}>
        {row.productName}
      </div>
      <div className="mt-0.5 flex flex-wrap items-center gap-x-1.5 gap-y-0.5 text-xs text-muted-foreground">
        <span className={type === "deduct" ? "text-danger" : "text-success"}>{t(TYPE_KEYS[type])}</span>
        <span className="font-medium text-foreground">{type === "deduct" ? `-${qty}` : `+${qty}`}</span>
        <span>· {row.reason}</span>
        <InventoryStatusBadge status={row.status} />
      </div>
    </div>
  )
}

export function getInventoryListExpandedColumns({
  onEdit,
  onApprove,
  onReject,
  onMap,
  density = "full",
}: {
  density?: InventoryListDensity
  onEdit?: (movement: StockMovementRow) => void
  // Admin-only approval actions on pending rows (see ApprovalActionsCell);
  // omitted, there's no Approve column.
  onApprove?: (movement: StockMovementRow) => void
  onReject?: (movement: StockMovementRow) => void
  onMap?: (movement: StockMovementRow) => void
} = {}): ColumnDef<StockMovementRow, unknown>[] {
  const actionsCell = (movement: StockMovementRow) => (
    <div className="flex items-center gap-1">
      {onApprove && onReject && onMap && <ApprovalActionsCell movement={movement} onApprove={onApprove} onReject={onReject} onMap={onMap} />}
      {onEdit && <EditButtonCell movement={movement} onEdit={onEdit} className="h-7 w-7 p-0" />}
    </div>
  )
  if (density === "compact") {
    return [
      { accessorKey: "productName", header: () => <ColumnHeader tKey="item" ns="inventory" />, cell: ({ row }) => <CompactItemCell row={row.original} /> },
      {
        accessorKey: "relatedJobOrderNo",
        header: () => <ColumnHeader tKey="relatedJob" ns="inventory" />,
        cell: ({ row }) => (
          <span className="block max-w-[8rem] truncate" title={row.original.relatedJobOrderNo}>
            {row.original.relatedJobOrderNo || "—"}
          </span>
        ),
      },
      ...(onApprove || onEdit ? [{ id: "actions", header: "", cell: ({ row }) => actionsCell(row.original) } as ColumnDef<StockMovementRow, unknown>] : []),
    ]
  }

  const columns: ColumnDef<StockMovementRow, unknown>[] = [
    {
      accessorKey: "productName",
      header: () => <ColumnHeader tKey="item" ns="inventory" />,
      cell: ({ row }) => (
        <span className={cn("block truncate", density === "medium" ? "max-w-[14rem]" : "max-w-[22rem]")} title={row.original.productName}>
          {row.original.productName}
        </span>
      ),
    },
    { id: "type", header: () => <ColumnHeader tKey="type" ns="inventory" />, cell: ({ row }) => <TypeCell row={row.original} /> },
    { id: "qty", header: () => <ColumnHeader tKey="quantity" ns="fields" />, cell: ({ row }) => <QtyCell row={row.original} /> },
    {
      accessorKey: "reason",
      header: () => <ColumnHeader tKey="reason" ns="inventory" />,
      cell: ({ row }) => <ReasonCell row={row.original} />,
    },
    {
      accessorKey: "relatedJobOrderNo",
      header: () => <ColumnHeader tKey="relatedJob" ns="inventory" />,
      // A per-item total (aggregateInventoryRowsByItem) lists every order.
      cell: ({ row }) => <span className="block max-w-[18rem] whitespace-normal">{row.original.relatedJobOrderNo || "—"}</span>,
    },
    {
      accessorKey: "status",
      header: () => <ColumnHeader tKey="status" ns="fields" />,
      cell: ({ row }) => <InventoryStatusBadge status={row.original.status} />,
    },
    ...(density === "medium" ? [] : [
    { accessorKey: "userName", header: () => <ColumnHeader tKey="createdBy" ns="inventory" /> } as ColumnDef<StockMovementRow, unknown>,
    {
      accessorKey: "approvedByName",
      header: () => <ColumnHeader tKey="approvedBy" ns="inventory" />,
      cell: ({ row }) => row.original.approvedByName || "—",
    } as ColumnDef<StockMovementRow, unknown>,
    {
      accessorKey: "createdAt",
      header: () => <ColumnHeader tKey="time" ns="inventory" />,
      cell: ({ row }) => formatDateTime(row.original.createdAt),
    } as ColumnDef<StockMovementRow, unknown>,
    ]),
  ]
  if (onApprove && onReject && onMap) {
    columns.push({
      id: "approve",
      header: "",
      cell: ({ row }) => <ApprovalActionsCell movement={row.original} onApprove={onApprove} onReject={onReject} onMap={onMap} />,
    })
  }
  if (onEdit) {
    columns.push({
      id: "edit",
      header: "",
      // A row combining several movements (mergedIds) opens the grouped edit
      // form, which edits each combined entry (StockMovementFormDialog).
      cell: ({ row }) => <EditButtonCell movement={row.original} onEdit={onEdit} />,
    })
  }
  return columns
}

// The Inventory List shows one row per item per job: several movements a job
// queued for the same item (e.g. a repair with two part rows for 012, or a
// schedule job's recorded filter items) are combined into a single row with
// the total quantity. Only merges trigger-created job movements that agree
// on job, item, direction, reason and status — a manual entry, or two jobs,
// are never combined. Display only: the stored movements stay one per
// recorded part/item, so each still links back to what created it.
export function groupInventoryListRows(rows: StockMovementRow[]): StockMovementRow[] {
  const out: StockMovementRow[] = []
  const byKey = new Map<string, StockMovementRow>()
  for (const r of rows) {
    const job = r.filterChangePlanId ?? r.installPlanId ?? r.scheduleJobId ?? (r.repairPlanPartId ? `rep:${r.relatedJobOrderNo ?? r.referenceNumber}` : undefined)
    if (!job) {
      out.push(r)
      continue
    }
    const direction = r.quantityAdded > 0 && r.quantityRemoved === 0 ? "in" : "out"
    const key = [job, r.productId || r.itemLabel, direction, r.reason, r.status].join("|")
    const existing = byKey.get(key)
    if (!existing) {
      const copy = { ...r, mergedIds: [r.id] }
      byKey.set(key, copy)
      out.push(copy)
      continue
    }
    existing.quantityAdded += r.quantityAdded
    existing.quantityRemoved += r.quantityRemoved
    existing.mergedIds = [...(existing.mergedIds ?? [existing.id]), r.id]
    if (r.createdAt > existing.createdAt) existing.createdAt = r.createdAt
  }
  return out
}

// The Inventory List modal's per-item totals: every row for the same item
// moving the same way with the same status is combined into one, across
// jobs — e.g. three 012 Pre-Carbon filters used on three visits become one
// "-3" row whose Related Job lists all three orders. Pending and approved
// rows are never combined (a total must be all one or the other), nor IN
// with OUT. Reason, Created By and Approved By list each distinct value.
export function aggregateInventoryRowsByItem(rows: StockMovementRow[]): StockMovementRow[] {
  const out: StockMovementRow[] = []
  const byKey = new Map<string, StockMovementRow>()
  const joinDistinct = (a: string | undefined, b: string | undefined) => {
    const parts = [...new Set([...(a ?? "").split(", "), ...(b ?? "").split(", ")].map((x) => x.trim()).filter(Boolean))]
    return parts.length > 0 ? parts.join(", ") : undefined
  }
  for (const r of rows) {
    const direction = r.quantityAdded > 0 && r.quantityRemoved === 0 ? "in" : "out"
    const key = [r.productId || `label:${r.itemLabel}`, direction, r.status].join("|")
    const existing = byKey.get(key)
    if (!existing) {
      const copy = { ...r, mergedIds: r.mergedIds ?? [r.id] }
      byKey.set(key, copy)
      out.push(copy)
      continue
    }
    existing.quantityAdded += r.quantityAdded
    existing.quantityRemoved += r.quantityRemoved
    existing.mergedIds = [...(existing.mergedIds ?? [existing.id]), ...(r.mergedIds ?? [r.id])]
    existing.relatedJobOrderNo = joinDistinct(existing.relatedJobOrderNo, r.relatedJobOrderNo)
    existing.reason = (joinDistinct(existing.reason, r.reason) ?? existing.reason) as StockMovementRow["reason"]
    existing.userName = joinDistinct(existing.userName, r.userName) ?? existing.userName
    existing.approvedByName = joinDistinct(existing.approvedByName, r.approvedByName)
    if (r.createdAt > existing.createdAt) existing.createdAt = r.createdAt
  }
  return out
}

// Print/export column headers stay in English regardless of interface
// language — deferred to the long-tail phase alongside the other modules'
// export column arrays (see the phased i18n plan).
export const INVENTORY_LIST_EXPORT_COLUMNS = [
  { header: "Item", key: "productName" },
  { header: "Reason", key: "reason" },
  { header: "Source", key: "source" },
  { header: "Qty Added", key: "quantityAdded" },
  { header: "Qty Removed", key: "quantityRemoved" },
  { header: "Related Customer", key: "relatedCustomerName" },
  { header: "Related Job", key: "relatedJobOrderNo" },
  { header: "Status", key: "status" },
  { header: "Created By", key: "userName" },
  { header: "Approved By", key: "approvedByName" },
]
